[package]
name = "rvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = {version = "2.32", features = ["yaml"]}
nom = "7"
uuid = {version = "0.8", features=  ["v4"]}
